{
 "title": "Arris Modem",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "downstream_channel",
    "query": "select DISTINCT(\"channel_id\") from (select power, channel_id from downstream_statistics WHERE $timeFilter)"
   },
   {
    "name": "upstream_channel",
    "query": "select DISTINCT(\"channel_id\") from (select power, channel_id from upstream_statistics WHERE $timeFilter)"
   }
  ]
 },
 "panels": [
  {
   "title": "Max Uncorrectables",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT mean(\"corrected\") FROM \"downstream_statistics\" WHERE (\"channel_id\" =~ /^$downstream_channel$/) AND $timeFilter GROUP BY time($__interval), \"channel_id\" fill(null)",
     "select": [
      [
       { "params": [ "uncorrectables" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Downstream Stats",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "modulation" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT last(\"corrected\") AS \"corrected\", last(\"frequency\") AS \"frequency\", last(\"power\") AS \"power\", last(\"snr\") AS \"snr\", last(\"uncorrectables\") AS \"uncorrectables\" FROM \"downstream_statistics\" WHERE (\"channel_id\" =~ /^$downstream_channel$/) AND $timeFilter GROUP BY \"channel_id\" fill(none)",
     "select": [
      [
       { "params": [ "corrected" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "corrected" ], "type": "alias" }
      ],
      [
       { "params": [ "frequency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "frequency" ], "type": "alias" }
      ],
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "power" ], "type": "alias" }
      ],
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "snr" ], "type": "alias" }
      ],
      [
       { "params": [ "uncorrectables" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "uncorrectables" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS 3.0 Downstream Corrected (non-negative derivative)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Channel $tag_channel_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "corrected" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" },
      { "condition": "AND", "key": "modulation", "operator": "!=", "value": "OFDM PLC" }
     ]
    }
   ]
  },
  {
   "title": "Downstream Uncorrectables (non-negative derivative)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Channel $tag_channel_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "uncorrectables" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Downstream SNR / MER",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "Channel $tag_channel_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Downstream Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "alias": "Channel $tag_channel_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS 3.1 OFDM Downstream Corrected (non-negative derivative)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "alias": "Channel $tag_channel_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "corrected" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" },
      { "condition": "AND", "key": "modulation", "operator": "=", "value": "OFDM PLC" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "alias": "Channel $tag_channel_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "upstream_statistics",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$upstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Upstream Stats",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "channel_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "upstream_statistics",
     "select": [
      [
       { "params": [ "frequency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "frequency" ], "type": "alias" }
      ],
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "power" ], "type": "alias" }
      ],
      [
       { "params": [ "width" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "width" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$upstream_channel$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
   "options": {
    "content": "<center><h1>Downstream Stats</h1></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Channel  $downstream_channel - Uncorrectables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "repeat": "downstream_channel",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Uncorrectables",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT mean(\"uncorrectables\") FROM \"downstream_statistics\" WHERE (\"channel_id\" =~ /^$downstream_channel$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "uncorrectables" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Channel  $downstream_channel - Corrected",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "repeat": "downstream_channel",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Corrected",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT mean(\"uncorrectables\") FROM \"downstream_statistics\" WHERE (\"channel_id\" =~ /^$downstream_channel$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "corrected" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Channel  $downstream_channel - Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "repeat": "downstream_channel",
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT mean(\"uncorrectables\") FROM \"downstream_statistics\" WHERE (\"channel_id\" =~ /^$downstream_channel$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Channel  $downstream_channel - SNR / MER",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "repeat": "downstream_channel",
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "SNR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT mean(\"uncorrectables\") FROM \"downstream_statistics\" WHERE (\"channel_id\" =~ /^$downstream_channel$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  }
 ]
}